# Generated by Django 5.0 on 2024-01-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accademicYear',
            new_name='academicYear',
        ),
        migrations.AlterModelTable(
            name='academicyear',
            table='academic_year',
        ),
        migrations.AlterModelTable(
            name='studentclass',
            table='student_class',
        ),
    ]
